import type { School } from '@/types';

export const CUSTOM_SCHOOL_ID = 'custom';

/** Fallback used when the user's school isn't in the list. */
export const defaultSchool: School = {
  id: CUSTOM_SCHOOL_ID,
  name: 'My School',
  shortName: 'My School',
  region: 'south',
  style: 'fall_formal',
  recs: 'recommended',
  costTier: 2,
  chapterCount: 10,
  rushMonth: 8,
  registrationOpensMonthsBefore: 3,
  notes: 'Check your campus Panhellenic site for exact dates and rec-letter policy.',
};

export const schools: School[] = [
  {
    id: 'alabama',
    name: 'University of Alabama',
    shortName: 'Alabama',
    region: 'south',
    style: 'fall_formal',
    recs: 'recommended',
    costTier: 3,
    chapterCount: 17,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes:
      'The biggest, most competitive rush in the country (~2,500 PNMs). RIFs accepted but not required; chapters pre-screen heavily. First-year costs can top $8,000.',
  },
  {
    id: 'ole-miss',
    name: 'University of Mississippi',
    shortName: 'Ole Miss',
    region: 'south',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 12,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Classic Southern rush — rec letters expected for every chapter, fall recruitment before classes.',
  },
  {
    id: 'georgia',
    name: 'University of Georgia',
    shortName: 'UGA',
    region: 'south',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 20,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Largest Panhellenic community by chapter count (20). Recs strongly expected; Bid Day on Milledge Avenue.',
  },
  {
    id: 'auburn',
    name: 'Auburn University',
    shortName: 'Auburn',
    region: 'south',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 18,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Fourth-largest formal recruitment in the country; record 2,153 new members in 2025 (92% bid rate).',
  },
  {
    id: 'lsu',
    name: 'Louisiana State University',
    shortName: 'LSU',
    region: 'south',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 12,
    rushMonth: 8,
    registrationOpensMonthsBefore: 4,
    notes: 'Registration is only $165 but recs matter. LSU also publishes official STAR chapter ratings — use those over gossip tiers.',
  },
  {
    id: 'tennessee',
    name: 'University of Tennessee',
    shortName: 'Tennessee',
    region: 'south',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 14,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'SEC rec-heavy pattern; fall recruitment the week before classes.',
  },
  {
    id: 'arkansas',
    name: 'University of Arkansas',
    shortName: 'Arkansas',
    region: 'south',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 12,
    rushMonth: 8,
    registrationOpensMonthsBefore: 4,
    notes: '~2,200+ PNMs; $330 registration; RIFs emphasized. Chapter accounts stop following PNMs after spring break.',
  },
  {
    id: 'miss-state',
    name: 'Mississippi State University',
    shortName: 'Miss State',
    region: 'south',
    style: 'fall_formal',
    recs: 'required',
    costTier: 2,
    chapterCount: 9,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Deep-South rec culture with slightly lower costs than the flagship SEC schools.',
  },
  {
    id: 'florida',
    name: 'University of Florida',
    shortName: 'UF',
    region: 'southeast',
    style: 'fall_formal',
    recs: 'recommended',
    costTier: 2,
    chapterCount: 18,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Large fall rush; recs helpful but less mandatory than the deep South.',
  },
  {
    id: 'fsu',
    name: 'Florida State University',
    shortName: 'FSU',
    region: 'southeast',
    style: 'fall_formal',
    recs: 'recommended',
    costTier: 2,
    chapterCount: 17,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Big, spirited fall recruitment with its own tier folklore — treat rankings as gossip, not data.',
  },
  {
    id: 'south-carolina',
    name: 'University of South Carolina',
    shortName: 'South Carolina',
    region: 'southeast',
    style: 'fall_formal',
    recs: 'recommended',
    costTier: 2,
    chapterCount: 14,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: '$185 registration; fall recruitment; recs helpful.',
  },
  {
    id: 'clemson',
    name: 'Clemson University',
    shortName: 'Clemson',
    region: 'southeast',
    style: 'fall_formal',
    recs: 'recommended',
    costTier: 1,
    chapterCount: 13,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'One of the most affordable Greek systems in the Southeast (~$820 new-member dues).',
  },
  {
    id: 'texas',
    name: 'University of Texas at Austin',
    shortName: 'UT Austin',
    region: 'texas',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 14,
    rushMonth: 8,
    registrationOpensMonthsBefore: 4,
    notes: 'Competitive, rec-driven Texas rush before fall classes.',
  },
  {
    id: 'texas-am',
    name: 'Texas A&M University',
    shortName: 'Texas A&M',
    region: 'texas',
    style: 'fall_formal',
    recs: 'required',
    costTier: 2,
    chapterCount: 14,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: '~3,800 sorority women but proportionally smaller Greek footprint (~11% of undergrads).',
  },
  {
    id: 'tcu',
    name: 'Texas Christian University',
    shortName: 'TCU',
    region: 'texas',
    style: 'fall_formal',
    recs: 'required',
    costTier: 3,
    chapterCount: 13,
    rushMonth: 8,
    registrationOpensMonthsBefore: 4,
    notes: 'Competitive private-school rush with strong rec culture.',
  },
  {
    id: 'smu',
    name: 'Southern Methodist University',
    shortName: 'SMU',
    region: 'texas',
    style: 'deferred_spring',
    recs: 'required',
    costTier: 3,
    chapterCount: 8,
    rushMonth: 1,
    registrationOpensMonthsBefore: 3,
    notes:
      'Deferred January rush — and recs must be sent DIRECTLY to each house (they are discarded if sent to Panhellenic). Coaches advise recs done by May 1.',
  },
  {
    id: 'oklahoma',
    name: 'University of Oklahoma',
    shortName: 'OU',
    region: 'texas',
    style: 'fall_formal',
    recs: 'required',
    costTier: 2,
    chapterCount: 13,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Rec-driven fall rush in the Texas/Oklahoma pattern.',
  },
  {
    id: 'ohio-state',
    name: 'Ohio State University',
    shortName: 'Ohio State',
    region: 'midwest',
    style: 'fall_formal',
    recs: 'not_used',
    costTier: 2,
    chapterCount: 15,
    rushMonth: 9,
    registrationOpensMonthsBefore: 2,
    notes: 'RIFs accepted but not needed; recruitment runs after classes start.',
  },
  {
    id: 'indiana',
    name: 'Indiana University',
    shortName: 'Indiana',
    region: 'midwest',
    style: 'deferred_spring',
    recs: 'not_used',
    costTier: 2,
    chapterCount: 19,
    rushMonth: 1,
    registrationOpensMonthsBefore: 3,
    notes:
      'Spring primary recruitment with ~1,800 PNMs. Top houses reportedly invite back only ~30% after Round 1, and GPA can be a hard cut line — keep grades up in the fall.',
  },
  {
    id: 'purdue',
    name: 'Purdue University',
    shortName: 'Purdue',
    region: 'midwest',
    style: 'deferred_spring',
    recs: 'not_used',
    costTier: 1,
    chapterCount: 14,
    rushMonth: 1,
    registrationOpensMonthsBefore: 3,
    notes: 'Deferred spring recruitment; lower-cost Midwest Greek life.',
  },
  {
    id: 'michigan',
    name: 'University of Michigan',
    shortName: 'Michigan',
    region: 'midwest',
    style: 'deferred_spring',
    recs: 'not_used',
    costTier: 2,
    chapterCount: 16,
    rushMonth: 1,
    registrationOpensMonthsBefore: 3,
    notes: 'Winter recruitment in January; conversation-driven, no recs.',
  },
  {
    id: 'penn-state',
    name: 'Penn State University',
    shortName: 'Penn State',
    region: 'northeast',
    style: 'deferred_spring',
    recs: 'not_used',
    costTier: 2,
    chapterCount: 15,
    rushMonth: 1,
    registrationOpensMonthsBefore: 3,
    notes: 'Spring recruitment; no rec letters needed.',
  },
  {
    id: 'cornell',
    name: 'Cornell University',
    shortName: 'Cornell',
    region: 'northeast',
    style: 'deferred_spring',
    recs: 'not_used',
    costTier: 1,
    chapterCount: 11,
    rushMonth: 1,
    registrationOpensMonthsBefore: 3,
    notes:
      'Deferred January recruitment since the 1950s. Cornell does not collect recs or legacy info at all — conversation is everything.',
  },
  {
    id: 'northwestern',
    name: 'Northwestern University',
    shortName: 'Northwestern',
    region: 'midwest',
    style: 'deferred_spring',
    recs: 'not_used',
    costTier: 1,
    chapterCount: 10,
    rushMonth: 1,
    registrationOpensMonthsBefore: 2,
    notes: 'Deferred winter recruitment; low-stakes and conversation-driven.',
  },
  {
    id: 'duke',
    name: 'Duke University',
    shortName: 'Duke',
    region: 'southeast',
    style: 'deferred_spring',
    recs: 'not_used',
    costTier: 1,
    chapterCount: 9,
    rushMonth: 1,
    registrationOpensMonthsBefore: 2,
    notes: 'Deferred spring recruitment, unhoused chapters, much lower cost.',
  },
  {
    id: 'asu',
    name: 'Arizona State University',
    shortName: 'ASU',
    region: 'west',
    style: 'fall_formal',
    recs: 'not_used',
    costTier: 2,
    chapterCount: 15,
    rushMonth: 8,
    registrationOpensMonthsBefore: 3,
    notes: 'Big, social West Coast-style rush; no recs; more casual appearance norms.',
  },
  {
    id: 'ucla',
    name: 'University of California, Los Angeles',
    shortName: 'UCLA',
    region: 'west',
    style: 'fall_formal',
    recs: 'not_used',
    costTier: 2,
    chapterCount: 13,
    rushMonth: 9,
    registrationOpensMonthsBefore: 3,
    notes: 'Fall rush after move-in; lower cost (new-member dues up to ~$1,700), casual vibe, no recs.',
  },
];

export function getSchoolById(id: string | null): School | undefined {
  if (!id) return undefined;
  return schools.find((s) => s.id === id);
}
